# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_directory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Directory',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp', '-updated']},
        ),
    ]
